### PR TITLE
Viz first page

### PR DESCRIPTION
**Pull request by PadmanabhanAshwin**
Country color coded. 

Before merging:

1. Style considerations (fill color, stroke color) in congruence with overarching theme. 
2. Delay (speed) of animation. 
3. Adding/style tooltip.

### CODE REVIEW

**Comment by PadmanabhanAshwin** [comment]
Tool tip completed. 

Style before merge.

**Comment by PadmanabhanAshwin** [comment]
Tooltip commit done. Style before merging.

**Comment by PadmanabhanAshwin** [comment]
Line color variable added.

Before merging styling for:

1. Line. 
2. Tooltip. 
3. Dropdown

**Review by meenurajapandian — COMMENTED** [review]
Styling changed. Needs to be added to the page

**Pull request merged**
